CREATE TABLE final_labor.commission (commission_id BIGINT AUTO_INCREMENT NOT NULL, professor BIGINT, topic_of_student_labor BIGINT, PRIMARY KEY (commission_id))
CREATE TABLE final_labor.professor (professor_id BIGINT AUTO_INCREMENT NOT NULL, professor_lastname VARCHAR(255) NOT NULL, professor_name VARCHAR(255) NOT NULL, professor_email VARCHAR(255) NOT NULL, PRIMARY KEY (professor_id))
CREATE TABLE final_labor.student (student_id BIGINT AUTO_INCREMENT NOT NULL, espb INTEGER NOT NULL, nbi VARCHAR(255) NOT NULL, semester INTEGER NOT NULL, student_email VARCHAR(255) NOT NULL, student_lastname VARCHAR(255) NOT NULL, student_name VARCHAR(255) NOT NULL, study_program VARCHAR(255) NOT NULL, PRIMARY KEY (student_id))
CREATE TABLE final_labor.topic (topic_id BIGINT AUTO_INCREMENT NOT NULL, field_of_interesting VARCHAR(255), description VARCHAR(255), topic_name VARCHAR(255) NOT NULL, professor BIGINT NOT NULL, PRIMARY KEY (topic_id))
CREATE TABLE final_labor.topic_of_student_labor (TOPICOFSTUDENTLABORID BIGINT AUTO_INCREMENT NOT NULL, topic BIGINT, student BIGINT, PRIMARY KEY (TOPICOFSTUDENTLABORID))
ALTER TABLE final_labor.commission ADD CONSTRAINT FK_commission_professor FOREIGN KEY (professor) REFERENCES final_labor.professor (professor_id)
ALTER TABLE final_labor.commission ADD CONSTRAINT FK_commission_topic_of_student_labor FOREIGN KEY (topic_of_student_labor) REFERENCES final_labor.topic_of_student_labor (TOPICOFSTUDENTLABORID)
ALTER TABLE final_labor.topic ADD CONSTRAINT FK_topic_professor FOREIGN KEY (professor) REFERENCES final_labor.professor (professor_id)
ALTER TABLE final_labor.topic_of_student_labor ADD CONSTRAINT FK_topic_of_student_labor_topic FOREIGN KEY (topic) REFERENCES final_labor.topic (topic_id)
ALTER TABLE final_labor.topic_of_student_labor ADD CONSTRAINT FK_topic_of_student_labor_student FOREIGN KEY (student) REFERENCES final_labor.student (student_id)
